//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from 'cs2/utils';

export class UIBindingConstants
{
	public static DEBUG_TEXTS: string = `debugTexts`;
	public static IS_DEBUG: string = `isDebugEnabled`;
	public static SET_VISIBILITY: string = `setVisibility`;
	public static TOGGLE_TOOL: string = `toggleTool`;
	public static SET_ACTION_OVERLAY_PREVIEW: string = `setActionOverlayPreview`;
	public static SELECTED_INTERSECTION: string = `selectedIntersection`;
	public static APPLY_TOOL_ACTION_PREVIEW: string = `applyToolActionPreview`;
	public static LANE_CONNECTOR_TOOL: string = `Lane Connector Tool`;
}
export class UIKeys
{
	public static TRAFFIC_MOD: string = `Traffic.UI.Tooltip.MainButton`;
	public static LANE_CONNECTION_TOOL: string = `Traffic.Tools.LaneConnector[Title]`;
	public static SELECT_INTERSECTION: string = `Traffic.Tools.LaneConnector[SelectIntersectionMessage]`;
	public static REMOVE_ALL_CONNECTIONS: string = `Traffic.Tools.LaneConnector.Toolbox[RemoveAllConnections]`;
	public static REMOVE_U_TURNS: string = `Traffic.Tools.LaneConnector.Toolbox[RemoveUturns]`;
	public static REMOVE_UNSAFE: string = `Traffic.Tools.LaneConnector.Toolbox[RemoveUnsafe]`;
	public static RESET_TO_VANILLA: string = `Traffic.Tools.LaneConnector.Toolbox[ResetToVanilla]`;
	public static REMOVE_UNSAFE_TOOLTIP_TITLE: string = `Traffic.Tools.LaneConnector.Toolbox[ResetToVanilla].Tooltip.Title`;
	public static REMOVE_UNSAFE_TOOLTIP_MESSAGE: string = `Traffic.Tools.LaneConnector.Toolbox[ResetToVanilla].Tooltip.Message`;
}
export enum TempFlags {
	Create = 1,
	Delete = 2,
	IsLast = 4,
	Essential = 8,
	Dragging = 16,
	Select = 32,
	Modify = 64,
	Regenerate = 128,
	Replace = 256,
	Upgrade = 512,
	Hidden = 1024,
	Parent = 2048,
	Combine = 4096,
	RemoveCost = 8192,
	Optional = 16384,
	Cancel = 32768,
	SubDetail = 65536
}
export enum ActionOverlayPreview {
	None = 0,
	RemoveAllConnections = 1,
	RemoveUTurns = 2,
	RemoveUnsafe = 3,
	ResetToVanilla = 4
}
export interface float3
{
	x: number;
	y: number;
	z: number;
}
export interface DebugData
{
	entity: Entity;
	position: float3;
	position2d: float3;
	value: string;
	isEdge: boolean;
	isTemp: boolean;
	flags: TempFlags;
	original: Entity;
	originalIsEdge: boolean;
}
export interface SelectedIntersectionData
{
	entity: Entity;
}
