//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Entity } from 'cs2/utils';
import { WidgetIdentifier } from 'cs2/bindings';

export class UIBindingConstants
{
	public static DEBUG_TEXTS: string = `debugTexts`;
	public static IS_DEBUG: string = `isDebugEnabled`;
	public static SET_VISIBILITY: string = `setVisibility`;
	public static TOGGLE_TOOL: string = `toggleTool`;
	public static KEY_BINDINGS: string = `keybindings`;
	public static TOOL_MODE: string = `toolMode`;
	public static CURRENT_TOOL_MODE: string = `currentToolMode`;
	public static OVERLAY_MODE: string = `overlayMode`;
	public static LANE_CONNECTOR_TOOL: string = `Lane Connector Tool`;
	public static PRIORITIES_TOOL: string = `Priorities Tool`;
	public static SET_ACTION_OVERLAY_PREVIEW: string = `setActionOverlayPreview`;
	public static SELECTED_INTERSECTION: string = `selectedIntersection`;
	public static APPLY_TOOL_ACTION_PREVIEW: string = `applyToolActionPreview`;
	public static LOADING_ERRORS_PRESENT: string = `loadingErrorsPresent`;
	public static ERROR_AFFECTED_INTERSECTIONS: string = `errorAffectedIntersection`;
	public static REMOVE_ENTITY_FROM_LIST: string = `removeEntityFromList`;
	public static NAVIGATE_TO_ENTITY: string = `navigateToEntity`;
}
export class UIKeys
{
	public static TRAFFIC_MOD: string = `Traffic.UI.Tooltip.MainButton`;
	public static SHORTCUT: string = `Traffic.UI.Tooltip.Shortcut`;
	public static LANE_CONNECTOR_TOOL: string = `Traffic.UI.Tools[LaneConnector].Title`;
	public static PRIORITIES_TOOL: string = `Traffic.UI.Tools[Priorities].Title`;
	public static SELECT_INTERSECTION: string = `Traffic.UI.Tools[LaneConnector].SelectIntersectionMessage`;
	public static REMOVE_ALL_CONNECTIONS: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveAllConnections]`;
	public static REMOVE_U_TURNS: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUturns]`;
	public static REMOVE_UNSAFE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUnsafe]`;
	public static RESET_TO_VANILLA: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[ResetToVanilla]`;
	public static PRIORITY_ACTION: string = `TrafficUI.Tools[Priorities].Toolbox.Action[Priority]`;
	public static YIELD_ACTION: string = `TrafficUI.Tools[Priorities].Toolbox.Action[Yield]`;
	public static STOP_ACTION: string = `TrafficUI.Tools[Priorities].Toolbox.Action[Stop]`;
	public static RESET_ACTION: string = `TrafficUI.Tools[Priorities].Toolbox.Action[Reset]`;
	public static REMOVE_ALL_CONNECTIONS_TOOLTIP_TITLE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveAllConnections].Tooltip.Title`;
	public static REMOVE_ALL_CONNECTIONS_TOOLTIP_MESSAGE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveAllConnections].Tooltip.Message`;
	public static REMOVE_U_TURNS_TOOLTIP_TITLE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUTurns].Tooltip.Title`;
	public static REMOVE_U_TURNS_TOOLTIP_MESSAGE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUTurns].Tooltip.Message`;
	public static REMOVE_UNSAFE_TOOLTIP_TITLE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUnsafe].Tooltip.Title`;
	public static REMOVE_UNSAFE_TOOLTIP_MESSAGE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[RemoveUnsafe].Tooltip.Message`;
	public static RESET_TO_VANILLA_TOOLTIP_TITLE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[ResetToVanilla].Tooltip.Title`;
	public static RESET_TO_VANILLA_TOOLTIP_MESSAGE: string = `Traffic.UI.Tools[LaneConnector].Toolbox.Action[ResetToVanilla].Tooltip.Message`;
	public static PRIORITY_ACTION_TOOLTIP: string = `Traffic.UI.Tools[Priorities].Toolbox.Action[Priority].Tooltip.Message`;
	public static YIELD_ACTION_TOOLTIP: string = `Traffic.UI.Tools[Priorities].Toolbox.Action[Yield].Tooltip.Message`;
	public static STOP_ACTION_TOOLTIP: string = `Traffic.UI.Tools[Priorities].Toolbox.Action[Stop].Tooltip.Message`;
	public static RESET_ACTION_TOOLTIP: string = `Traffic.UI.Tools[Priorities].Toolbox.Action[Reset].Tooltip.Message`;
	public static TOGGLE_DISPLAY_MODE_TOOLTIP: string = `Traffic.UI.Tools[Priorities].Toolbox.Action[ToggleDisplayMode].Tooltip.Message`;
}
export interface ModKeyBinds
{
	laneConnectorTool: WidgetIdentifier;
	prioritiesTool: WidgetIdentifier;
	removeAllConnections: WidgetIdentifier;
	removeUTurns: WidgetIdentifier;
	removeUnsafe: WidgetIdentifier;
	resetDefaults: WidgetIdentifier;
	toggleDisplayMode: WidgetIdentifier;
	usePriority: WidgetIdentifier;
	useYield: WidgetIdentifier;
	useStop: WidgetIdentifier;
	useReset: WidgetIdentifier;
}
export enum TempFlags {
	Create = 1,
	Delete = 2,
	IsLast = 4,
	Essential = 8,
	Dragging = 16,
	Select = 32,
	Modify = 64,
	Regenerate = 128,
	Replace = 256,
	Upgrade = 512,
	Hidden = 1024,
	Parent = 2048,
	Combine = 4096,
	RemoveCost = 8192,
	Optional = 16384,
	Cancel = 32768,
	SubDetail = 65536,
	Duplicate = 131072
}
export enum ActionOverlayPreview {
	None = 0,
	RemoveAllConnections = 1,
	RemoveUTurns = 2,
	RemoveUnsafe = 3,
	ResetToVanilla = 4
}
export enum PriorityToolSetMode {
	None = 0,
	Yield = 1,
	Stop = 2,
	Priority = 3,
	Reset = 4
}
export enum ModTool {
	None = 0,
	LaneConnector = 1,
	Priorities = 2
}
export enum OverlayMode {
	LaneGroup = 0,
	Lane = 1
}
export interface float3
{
	x: number;
	y: number;
	z: number;
}
export interface DebugData
{
	entity: Entity;
	position: float3;
	position2d: float3;
	value: string;
	isEdge: boolean;
	isTemp: boolean;
	flags: TempFlags;
	original: Entity;
	originalIsEdge: boolean;
}
export interface SelectedIntersectionData
{
	entity: Entity;
}
